name: Generate Space Shooter

on:
  schedule:
    - cron: "0 0 * * *" # Roda todo dia à meia-noite
  workflow_dispatch: # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: czl9707/gh-space-shooter@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
