name: Generate Space Shooter

on:
  schedule:
    - cron: "0 0 * * *" # Roda todo dia à meia-noite
  workflow_dispatch: # Isso permite que você aperte o botão para criar o GIF agora

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: czl9707/gh-space-shooter@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
